import Link from "next/link";
import {Hero} from "@chrishayuk/hause/components/forms/Hero";
import {publicationMetadata} from "@chrishayuk/hause/seo";
import {PRACTICES} from "@/data/practice";
import {KNOWLEDGE_NODES,relatedKnowledge} from "@/data/knowledge";
import film from "@/data/publication-film.json";
export const metadata=publicationMetadata({title:"HAUSE in practice",description:"How VINDEX3 and CHRISHAYUK shaped HAUSE: technical explanation, cinematic publication and the source record beneath both.",url:"https://hause.design/in-practice",siteName:"HAUSE",indexable:true,image:film.poster});
export default function Practice(){return <main><Hero kicker="REAL WORK / RECORDED CONTRIBUTIONS" title="BUILT BECAUSE A PAGE NEEDED IT." dek="A technical exhibition and a film-led research publication put different demands on the same language. Their contributions tell you what HAUSE is for."/>
 {PRACTICES.map(p=><section className="practice-story hause-grid" id={p.id} key={p.id}><div className="col-span-12 md:col-start-2 md:col-span-10"><p className="voice-evidence">{p.name} / {p.type}</p><h2 className="voice-editorial">{p.title}</h2><p className="voice-system">{p.summary}</p>{p.id==="chrishayuk"&&<Link href="/publication" className="story-film-frame"><img src={film.poster} alt="Chris Hay’s LARQL film, used in the publication specimen" loading="lazy"/><span className="voice-evidence">SEE THE SHARED FILM BEHAVIOUR ↗</span></Link>}<p className="voice-system">{p.contribution}</p><h3 className="voice-evidence">FOLLOW THE CONTRIBUTION</h3><div className="practice-contributions">{relatedKnowledge(`practice:${p.id}`).map(({node})=><Link href={node.url} key={node.id}>{node.title} ↗</Link>)}</div><div className="knowledge-actions"><Link href={p.recordUrl}>THE RECORDED EVIDENCE ↗</Link><a href={p.url}>{p.name} ↗</a></div></div></section>)}
 <section className="story-next hause-grid"><div className="col-span-12 md:col-start-2 md:col-span-10"><h2 className="voice-editorial">Keep your own world.</h2><p className="voice-system">HAUSE supplies the communicative forms and shared behaviour. The subject, editorial direction, imagery and publishing decisions belong to the consuming site.</p><Link href="/use" className="story-link">BUILD WITH HAUSE ↗</Link></div></section></main>;}
