import Image from 'next/image';
import { EditorialPlate } from '@chrishayuk/hause/components/EditorialPlate';
import { EXHIBITION_STUDIES } from '@/data/exhibition';
import { FolioObject, Marginalia } from '@chrishayuk/hause/components/Codex';
import { NotebookTemplate as Codex, NotebookNote, NotebookFilm, NotebookPreview } from '@chrishayuk/hause/components/NotebookTemplate';
import { YouTubeFilm } from '@chrishayuk/hause/components/YouTubeFilm';
import film from '@/data/publication-film.json';
import { Manuscript } from '@chrishayuk/hause/components/Manuscript';
import { NotebookEdition } from '@chrishayuk/hause/components/NotebookEdition';

/** A composition specimen, explicitly not an invented research history. */
export function PublicationCodex() {
 return <NotebookEdition as="article"><NotebookPreview title="Leave a notebook open." href="#publication-codex" summary="An index can offer a real passage before asking the reader to open the book." label="Open notebook specimen" metadata="HAUSE / Publication composition" annotation="The host selects a published record; HAUSE renders its opening."><p>Use a title, a date and an actual excerpt. The same paper carries the full notebook and its entrance, with the binding and margin preserved at a smaller scale.</p><p>This is a composition specimen, not a published research note.</p></NotebookPreview><Codex id="publication-codex" title="An entry you can handle." collection="HAUSE / Codex specimen" byline={<span>Composition study · no experiment results</span>}
  folios={[
   {id:'codex-margin-surface',label:'A margin sketch',children:<><FolioObject place="left"><h2>A drawing belongs beside the thought.</h2><p>Keep a small explanation on the same paper. The publication supplies its meaning; the notebook supplies its scale and placement.</p></FolioObject><FolioObject place="right"><NotebookNote title="An observation and its source" caption="01 / A reading relationship" sketch={<svg viewBox="0 0 180 130" role="img" aria-label="An observation points to its source record."><rect x="22" y="12" width="136" height="32"/><text x="90" y="33" textAnchor="middle">observation</text><path d="M90 47v32m-5-6 5 6 5-6"/><rect x="22" y="85" width="136" height="32"/><text x="90" y="106" textAnchor="middle">source record</text></svg>}><p>The diagram shows a relationship, not an experimental result. Its caption stays beside it when the page becomes narrow.</p></NotebookNote></FolioObject></>},
   {id:'codex-film-surface',label:'A mounted film',children:<FolioObject place="full"><NotebookFilm marker="From the original film" timestamp="0:00" caption={film.title} source={{href: film.url,label:'Watch the source'}}><YouTubeFilm youtubeId={film.youtubeId} title={film.title} poster={film.poster}/></NotebookFilm><p>The frame sits on the paper. Playback still requires an explicit action, and the original source remains attached.</p></FolioObject>},
   {id:'codex-image-surface',label:'An image',children:<><FolioObject place="full"><EditorialPlate caption={<><span>Copper / attention</span><span>AI-generated visual study · fictional installation</span></>}><Image src={EXHIBITION_STUDIES.attention.src} alt={EXHIBITION_STUDIES.attention.alt} width={1536} height={1024} sizes="(max-width: 900px) 100vw, 1100px"/></EditorialPlate></FolioObject><FolioObject place="left"><h2>An image can occupy a spread.</h2></FolioObject><FolioObject place="right"><p>Let its scale establish a pause, then return to the account. The caption keeps the image’s origin visible.</p></FolioObject></>},
   {id:'codex-reading-surface',label:'A spread',children:<><FolioObject place="left"><h2>The page is a working surface.</h2><p>Keep an observation beside its object, with the qualification attached.</p></FolioObject><FolioObject place="right"><p>This specimen uses native text and layout. Your instruments, photographs and measurements occupy the same surface.</p></FolioObject><FolioObject place="margin"><Marginalia label="Source"><p>This is a typography and interaction specimen. It contains no measured result.</p></Marginalia></FolioObject></>},
   {id:'codex-evidence-surface',label:'An attached record',kind:'evidence',children:<><FolioObject place="main"><h2>Every object can lead back to its record.</h2><p>Evidence navigation is an ordinary fragment link. The view opens its destination; text remains selectable.</p><a href="/publication#recorded-evidence">Inspect the actual ADDRESS-BUILD-1 measurements ↗</a></FolioObject><FolioObject place="margin"><Marginalia label="Reading order"><p>Spread numbers describe this composition. They are not historical manuscript identifiers.</p></Marginalia></FolioObject></>},
  ]}
  manuscript={<Manuscript introduction={<p>The reading edition carries the full argument behind the working spreads.</p>} contents={<ol><li><a href="#specimen-reading-sequence">A continuous sequence</a></li><li><a href="#specimen-reading-objects">Return to the objects</a></li></ol>}><section id="specimen-reading-sequence" className="manuscript-chapter"><h3>A continuous sequence</h3><p>The folios let a reader encounter an observation beside an instrument or a measurement. Their short passages explain what is on the desk. A manuscript has a different responsibility: explain how the question arose, describe the method, and carry the qualifications through to the conclusion.</p><p>Compose that account as ordinary paragraphs under clear section headings. The reading column keeps a consistent measure; each paragraph continues the thought without a repeated label or a new panel.</p></section><section id="specimen-reading-objects" className="manuscript-chapter"><h3>Return to the objects</h3><p>Sources and instruments can remain available through ordinary links. The reader can follow a reference into a spread, then return to the account. This specimen explains the publishing pattern; it contains no experimental findings.</p><a href="#codex-evidence-surface">Return to the attached record ↗</a></section></Manuscript>}
  history={<p>This composition specimen has no experimental revisions. The consuming publication supplies its own preserved editions and source history; the shell does not generate them.</p>}/></NotebookEdition>;
}
