"use client";

import { useState, type CSSProperties } from "react";
import { StudyChoices } from "./StudyChoices";
import { PARTS, PART_DETAILS, BYTE_FIELDS, fieldOffset, activeUnits, arrangement, cappedGrade } from "./mechanisms";

export function ArgumentArrangement({ progress }: { progress: number }) {
  return <div className="study-arrangement" aria-label="LOOK, ASK, TEST and SAY rearranged from a pile into a sequence">
    <div className="study-arrangement-line" style={{ opacity: progress }} aria-hidden="true" />
    {PARTS.map((part, i) => { const pos = arrangement(i, progress); return <div className="study-moving-block" key={part} style={{ left: pos.left + "%", top: pos.top + "%", "--block-index": i } as CSSProperties}><span className="voice-evidence">0{i + 1}</span><strong className="voice-evidence">{part}</strong></div>; })}
  </div>;
}

export function ArgumentParts({ phase }: { phase: number }) {
  return <div className="study-argument" data-phase={phase}>
    <p className="study-whole voice-editorial">{phase === 0 ? "One argument." : "The parts of an argument."}</p>
    <div className="study-parts">{PARTS.map((part, i) => <div key={part}><span className="voice-evidence">0{i + 1} / {part}</span><p className="voice-system">{PART_DETAILS[i]}</p></div>)}</div>
    <p className="study-result voice-editorial">{phase === 2 ? "A conclusion you can retrace." : phase === 1 ? "The parts are visible. The conclusion still waits." : "Its internal structure is not yet disclosed."}</p>
  </div>;
}

export function InstrumentInteraction({ name }: { name: string }) {
  const [step, setStep] = useState(0);
  const [position, setPosition] = useState(100);
  const [kept, setKept] = useState([true, false, true, false, true, false, true, false]);
  switch (name) {
    case "Decomposition": return <><ArgumentParts phase={step} /><StudyChoices labels={["The whole", "The parts", "The result"]} selected={step} onSelect={setStep} /></>;
    case "Comparison": return <><ArgumentArrangement progress={position / 100} /><label className="study-range voice-evidence">PILE → SEQUENCE<input aria-label="Rearrange the same four pieces" type="range" min="0" max="100" value={position} onChange={event => setPosition(Number(event.target.value))} /></label><p className="study-measure voice-evidence">4 PIECES / 4 IDENTITIES / {position}% THROUGH THE REARRANGEMENT</p></>;
    case "ExpertField": {
      const active = activeUnits(step);
      return <><div className="study-field" aria-label={"Active units: " + active.map(i => i + 1).join(", ")}>{Array.from({ length: 36 }, (_, i) => <span key={i} data-active={active.includes(i)} className="voice-evidence">{String(i + 1).padStart(2, "0")}</span>)}</div><div className="study-field-reading"><strong className="voice-evidence">6 <small>/ 36</small></strong><p className="voice-system">The question changes.<br />The whole field does not wake up.</p></div><StudyChoices labels={["Structure", "Language", "Movement"]} selected={step} onSelect={setStep} label="Routing scenario" /></>;
    }
    case "Variants": return <><div className="study-identity voice-evidence">OBJECT 07 / THE SAME IDENTITY IN EVERY EDITION</div><div className="study-variant" key={step} aria-live="polite">{step === 0 ? <p className="voice-editorial">Arrival.<br />Attention.<br />Understanding.</p> : step === 1 ? <div className="study-variant-diagram">{["ARRIVAL", "ATTENTION", "UNDERSTANDING"].map((label, i) => <div key={label}><span className="voice-evidence">0{i + 1}</span><strong className="voice-system">{label}</strong>{i < 2 && <span aria-hidden="true">↓</span>}</div>)}</div> : <div className="study-unavailable"><p className="voice-evidence">REQUESTED: AUDIO / HELD: TEXT, DIAGRAM</p><p className="voice-editorial">That edition<br />does not exist.</p><p className="voice-system">The object remains. The requested representation is absent.</p></div>}</div><StudyChoices labels={["Text", "Diagram", "Audio · absent"]} selected={step} onSelect={setStep} label="Available edition" /></>;
    case "Ladder": {
      const rungs = [{ name: "Draft", status: "PASSED", gate: "A complete argument is present.", detail: "The illustrative draft has a beginning, supporting material and an ending." }, { name: "Checked", status: "BUILDING", gate: "Every testable assertion has been checked against its source.", detail: "A draft cannot be promoted merely because its typography is finished." }, { name: "Released", status: "OPEN", gate: "The check is complete and the publication record identifies the release.", detail: "This gate remains open until the preceding condition is satisfied." }];
      return <div className="study-ladder">{rungs.map((rung, i) => <details key={rung.name} open={i === 1}><summary><span className="voice-evidence">0{i + 1} / {rung.status}</span><strong className="voice-editorial">{rung.name}</strong></summary><p className="voice-system">{rung.gate}</p><p className="voice-system study-muted">{rung.detail}</p></details>)}</div>;
    }
    case "Agreement": return <><div className="study-equivalence"><div><p className="voice-evidence">PATH A / SUM</p><span className="voice-system">2 + 3 + 5</span><strong className="voice-evidence">10</strong></div><span className="study-equals voice-editorial" aria-label={step ? "does not equal" : "equals"}>{step ? "≠" : "≡"}</span><div><p className="voice-evidence">PATH B / PRODUCT{step ? " + PERTURBATION" : ""}</p><span className="voice-system">{step ? "(2 × 5) + 1" : "2 × 5"}</span><strong className="voice-evidence">{step ? 11 : 10}</strong></div></div><p className="study-verdict voice-evidence" role="status">{step ? "FAIL / THE VALUES DISAGREE BY 1" : "PASS / TWO PATHS, THE SAME VALUE"}</p><StudyChoices labels={["Matching result", "Introduce mismatch"]} selected={step} onSelect={setStep} /></>;
    case "Derivation": {
      const grade = cappedGrade(step === 0 ? [] : step === 1 ? [1] : [1, 2]);
      const grades = ["Strong", "Limited", "Provisional"];
      return <><div className="study-derivation">{grades.map((label, i) => <div key={label} data-current={grade === i}><span className="voice-evidence">0{i + 1}</span><strong className="voice-editorial">{label}</strong><span className="voice-evidence">{grade === i ? "← DERIVED LEVEL" : ""}</span></div>)}</div><p className="study-verdict voice-system" role="status">{["No caps applied. Begin at the strongest grade.", "Single setting: evidence cannot support a general result.", "No repeat observation: the remaining result is provisional."][step]}</p><StudyChoices labels={["Start", "Cap: one setting", "Cap: no repeat"]} selected={step} onSelect={setStep} /></>;
    }
    case "ByteMap": return <><div className="study-byte-heading"><strong className="voice-evidence">32 <small>bytes</small></strong><span className="voice-evidence">ILLUSTRATIVE RECORD / OFFSET 0–31</span></div><div className="study-byte-bar" role="group" aria-label="Byte regions">{BYTE_FIELDS.map((field, i) => <button key={field.name} type="button" style={{ flex: field.bytes }} aria-pressed={step === i} aria-label={field.name + ", " + field.bytes + " bytes"} onClick={() => setStep(i)}><span className="voice-evidence">{field.bytes}</span></button>)}</div><div className="study-byte-table">{BYTE_FIELDS.map((field, i) => <button type="button" aria-pressed={step === i} onClick={() => setStep(i)} key={field.name}><span className="voice-evidence">{String(fieldOffset(i)).padStart(2, "0")}–{String(fieldOffset(i) + field.bytes - 1).padStart(2, "0")}</span><strong className="voice-system">{field.name}</strong><span className="voice-evidence">{field.bytes} B</span></button>)}</div><p className="study-verdict voice-system" role="status">{BYTE_FIELDS[step].meaning}</p></>;
    case "Gating": return <><div className="study-gate" data-step={step}><p className="voice-evidence">{["NARROW INPUT", "EXPANDED WORKING SPACE", "JUDGED CHANNELS", "COMPRESSED RESULT"][step]}</p><div className="study-gate-channels">{kept.map((keep, i) => <button type="button" disabled={step !== 2} aria-pressed={keep} aria-label={"Keep channel " + (i + 1)} onClick={() => setKept(previous => previous.map((value, j) => j === i ? !value : value))} data-kept={keep} key={i}><span className="voice-evidence">{i + 1}</span></button>)}</div><p className="voice-system">{step === 2 ? "Choose which channels survive." : step === 3 ? kept.filter(Boolean).length + " of 8 channels retained." : "The same material, given a different working width."}</p></div><StudyChoices labels={["Input", "Expand", "Judge", "Compress"]} selected={step} onSelect={setStep} /></>;
    case "Lens": return <><p className="study-identity voice-evidence">ONE SUBJECT / A CLAIM THAT OWES EVIDENCE</p><StudyChoices labels={["Learn", "Inspect", "Contract"]} selected={step} onSelect={setStep} label="Depth of the explanation" /><div className="study-lens-view" aria-live="polite">{step === 0 ? <><p className="voice-editorial">A belief is not<br />a receipt.</p><p className="voice-system">A Claim states what you believe and how firmly it is supported. Evidence is the material that earns that support.</p></> : step === 1 ? <><p className="voice-evidence">OPEN / NO TEST SUPPLIED</p><p className="voice-editorial">Listeners prefer<br />the quieter room.</p><p className="voice-system">This illustrative assertion carries its unresolved status where the reader can see it.</p></> : <><p className="voice-evidence">CALLER RESPONSIBILITY</p><p className="voice-editorial">State the belief.<br />Declare the status.</p><p className="voice-system">The form does not verify the claim. The caller supplies the assertion, its status and the detail that explains the status.</p></>}</div><details className="study-transcript"><summary className="voice-evidence">ALL THREE DEPTHS / TEXT RECORD</summary><p className="voice-system">Learn: Claim states a belief; Evidence supplies its support. Inspect: “Listeners prefer the quieter room” remains OPEN without a test. Contract: the caller supplies the assertion, status and explanatory detail; the component does not verify them.</p></details></>;
    default: throw new Error(`No instrument interaction for ${name}`);
  }
}
