import Link from "next/link";
import {Hero} from "@chrishayuk/hause/components/forms/Hero";
import {Answer} from "@chrishayuk/hause/components/forms/Answer";
import {publicationMetadata} from "@chrishayuk/hause/seo";
import {EVALUATIONS} from "@/data/evaluations";
export const metadata=publicationMetadata({title:"Evidence: evaluations, methods and limits",description:"Inspect HAUSE’s published tests of form selection, question routing and machine understanding. Follow the results to their methods and source records.",url:"https://hause.design/evidence",siteName:"HAUSE",indexable:true});
export default function EvidenceIndex(){return <main><Hero kicker="EVIDENCE / READ THE TESTS" title="DOES IT WORK?" dek="A useful premise should survive inspection. Start with the question you care about, then read the method, result and limits together."/>
 <Answer question="What evidence exists for HAUSE?" answer="HAUSE publishes evaluations of form selection, question routing and what models learn from its website. These are scoped tests by the author, not proof of broad adoption. VINDEX3 and CHRISHAYUK demonstrate use in two publications by the same author; independent production reuse has not yet been established."/>
 <section className="evidence-index hause-grid"><div className="col-span-12 md:col-start-2 md:col-span-10">{EVALUATIONS.map(e=><article key={e.id}><p className="voice-evidence">{e.id.toUpperCase()}</p><h2 className="voice-editorial"><Link href={`/evals/${e.id}`}>{e.title} ↗</Link></h2><p className="voice-system">{e.text}</p><Link className="story-link" href={`/evals/${e.id}`}>READ THE EVALUATION ↗</Link></article>)}<article><p className="voice-evidence">ADOPTION & POSITIONING</p><h2 className="voice-editorial">Where the evidence ends.</h2><p className="voice-system">The case studies show how real pages shaped the library. A production implementation by another author is the next adoption proof point. It is an open task, not a case study this site can claim.</p><div className="inline-links"><Link className="story-link" href="/in-practice">SEE THE CURRENT EXAMPLES ↗</Link><Link className="story-link" href="/ai-native-design-systems">READ THE CATEGORY COMPARISON ↗</Link></div></article></div></section></main>;}
